# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Min's"
description: > # this means to ignore newlines until "email:"
   thoughts

email: mlee981001@gmail.mail
#blog logo
logo: "/assets/images/profile.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/desktop.JPG"

name: 'Min Lee'
author: 'Min Lee'
author_image: "/assets/images/profile.jpg"

paginate:	5

url: "https://minniie.github.io/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@dirkfabisch'
remote_theme: dirkfabisch/mediator

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
#  - icon:	facebook
#    url:	"" # https://www.facebook.com/minyoung.lee.mlee/
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="
  
  - icon: linkedin
    url: https://www.linkedin.com/in/minlee98/
    desc: Follow me on linkedin

  - icon:	github
    url:	https://github.com/minniie
    desc:	Fork me on github
   
  - icon: envelope
    url: mailto:mlee981001@gmail.com
    desc: Shoot me an email


# Math equation
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
